// <auto-generated />
using System;
using MTT.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MTT.Storage.Migrations
{
    [DbContext(typeof(DbNewsContext))]
    [Migration("20251107133518_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MTT.Storage.Entities.News", b =>
                {
                    b.Property<Guid>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_file_name");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NewsId");

                    b.ToTable("news", (string)null);

                    b.HasData(
                        new
                        {
                            NewsId = new Guid("03acc220-c687-46cf-b653-c87ec383943d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 7, 13, 35, 17, 702, DateTimeKind.Unspecified).AddTicks(4062), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageFileName = "dragon_attack.jpg",
                            ModifiedAt = new DateTimeOffset(new DateTime(2025, 11, 7, 13, 35, 17, 702, DateTimeKind.Unspecified).AddTicks(4062), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            NewsId = new Guid("48292e75-73ec-4c29-b513-2b983bcae2c8"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 7, 13, 35, 17, 702, DateTimeKind.Unspecified).AddTicks(4062), new TimeSpan(0, 0, 0, 0, 0)),
                            ImageFileName = "wizard_duel.png",
                            ModifiedAt = new DateTimeOffset(new DateTime(2025, 11, 7, 13, 35, 17, 702, DateTimeKind.Unspecified).AddTicks(4062), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("MTT.Storage.Entities.NewsTranslation", b =>
                {
                    b.Property<Guid>("TranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("translation_id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_id");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("subtitle");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("TranslationId");

                    b.HasIndex("NewsId", "Language")
                        .IsUnique()
                        .HasDatabaseName("IX_news_translation_unique_language_per_news");

                    b.ToTable("news_translation", (string)null);

                    b.HasData(
                        new
                        {
                            TranslationId = new Guid("214455be-d3b5-48f9-8c47-62a8055bddd6"),
                            Language = "en",
                            NewsId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Subtitle = "Chaos in the Northern Lands",
                            Text = "A wild dragon descended upon the village, causing panic and destruction.",
                            Title = "Dragon Attacks Village"
                        },
                        new
                        {
                            TranslationId = new Guid("5d6fec38-4d50-4a19-aeb6-b6e8956f1425"),
                            Language = "ru",
                            NewsId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Subtitle = "Хаос на севере",
                            Text = "Дикий дракон обрушился на деревню, вызвав панику и разрушения.",
                            Title = "Дракон атакует деревню"
                        },
                        new
                        {
                            TranslationId = new Guid("9240d82f-83c2-4e0b-9ef5-d15f7b2b89e1"),
                            Language = "en",
                            NewsId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Subtitle = "Magic Unleashed",
                            Text = "Two archmages clashed in the heart of the capital, unleashing powerful spells.",
                            Title = "Wizard Duel Shakes the Capital"
                        },
                        new
                        {
                            TranslationId = new Guid("e406c0b4-e8fc-4368-b6b5-f5ff355fd882"),
                            Language = "ru",
                            NewsId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Subtitle = "Магия без границ",
                            Text = "Два архимага столкнулись в центре столицы, выпуская мощные заклинания.",
                            Title = "Поединок магов потряс столицу"
                        });
                });

            modelBuilder.Entity("MTT.Storage.Entities.NewsTranslation", b =>
                {
                    b.HasOne("MTT.Storage.Entities.News", null)
                        .WithMany("Translations")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTT.Storage.Entities.News", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
